import{a as h,S as g,i}from"./assets/vendor-D73Uttp0.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))r(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&r(c)}).observe(document,{childList:!0,subtree:!0});function n(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function r(t){if(t.ep)return;t.ep=!0;const o=n(t);fetch(t.href,o)}})();const b="46932892-ab4a09809774f514baea4f6c0";async function L(e,s=1,n=15){try{const{data:r}=await h.get("https://pixabay.com/api/",{params:{key:b,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:n}});return r}catch(r){throw new Error(r.message)}}function v(e,s){const n=e.map(r=>`
        <a href="${r.largeImageURL}" class="gallery-item">
          <div class="image-card">
            <img src="${r.webformatURL}" alt="${r.tags}" />
            <div class="info">
              <p><b>Likes:</b> ${r.likes}</p>
              <p><b>Views:</b> ${r.views}</p>
              <p><b>Comments:</b> ${r.comments}</p>
              <p><b>Downloads:</b> ${r.downloads}</p>
            </div>
          </div>
        </a>
      `).join("");s.insertAdjacentHTML("beforeend",n)}function w(e){e.innerHTML=""}const q=document.querySelector(".search-form"),S=document.querySelector(".input-search"),p=document.querySelector(".results-container"),d=document.querySelector(".loader"),l=document.querySelector(".js-load-more");let u="",a=1;const f=15;let m=0,P=new g(".results-container .gallery-item",{captionsData:"alt",captionDelay:250});q.addEventListener("submit",e=>{if(e.preventDefault(),u=S.value.trim(),u===""){i.error({title:"Error",message:"Please enter a search term!"});return}a=1,m=0,w(p),y()});l.addEventListener("click",()=>{a+=1,y()});function y(){d.style.display="block",L(u,a,f).then(e=>{if(d.style.display="none",m=e.totalHits,e.hits.length===0&&a===1){i.info({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!"});return}v(e.hits,p),P.refresh(),a>1&&E(),a*f>=m?(l.classList.replace("load-more","load-more-hidden"),i.info({title:"End of results",message:"We're sorry, but you've reached the end of search results."})):l.classList.replace("load-more-hidden","load-more")}).catch(e=>{d.style.display="none",l.classList.replace("load-more","load-more-hidden"),i.error({title:"Error",message:"Failed to fetch images. Please try again later."})})}function E(){const e=document.querySelector(".gallery-item");if(e){const{height:s}=e.getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
